# Generated by Django 5.0.5 on 2024-07-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_champion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Champion',
        ),
    ]
